version: "3.9"

services:
  nlp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlp-api
    ports:
      - "8000:8000"
    volumes:
      - ./modelo_distilbert:/app/modelo_distilbert
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
